export const actions = {
    ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCESS:  'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',
    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
    TOGGLE_FILTER: 'TOGGLE_FILTER',
    
};